const doctorList = [
  "Dr. Asad",
  "Dr. Asim Mehmood",
  "Dr. Asim Rafiq",
  "Dr. Bakht Zaman",
  "Dr. Faizan Rauf",
  "Dr. Faraz Mehmood",
  "Dr. Farooq",
  "Dr. Fraz Mehmood",
  "Dr. Fouzia Malik",
  "Dr. Hammad",
  "Dr. Jibran Bari Khan",
  "Dr. M. Arif Qureshi",
  "Dr. Maj(R) Kashuf Abrar",
  "Dr. Mehnaz Kashif",
  "Dr. Muhammad Mubashir",
  "Dr. Noor-E-Hira",
  "Dr. Omer",
  "Dr. Qaisar Jahan",
  "Dr. Shahzad",
  "Dr. Shanza Arshad",
  "Dr. Sohail Chaudhary",
  "Dr. Uzma Ahmad",
  "Dr. Younas",
  "OT Technician",
  "Razia (Lhv)",
  "Self",
  "Thq"
];
export default doctorList;